### ISSUE TITLE
When a user makes a mistake in the register process, give them another chance

### ISSUE THREAD

**Issue by iwein** [StarterSquad/prudentia#13]
I often use `pwd | pbcopy` to copy absolute paths. Then I have the directory in my copy buffer and only have to type the file name right. Problem is that this adds an EOL at the end of the buffer too. Then this happens:

```
Do you want to register an existing droplet? [default: N]: n
Specify the absolute playbook path: /Users/iwein/projects/uCourse/deployment/boxes

Error: The absolute playbook path you entered is NOT a file.

(Prudentia > DigitalOcean) meh :(
```

Would be much friendlier if the cli did this:

```
Do you want to register an existing droplet? [default: N]: n
Specify the absolute playbook path: /Users/iwein/projects/uCourse/deployment/boxes

Error: The absolute playbook path you entered is NOT a file. Did you make a typo?

Specify the absolute playbook path: /Users/iwein/projects/uCourse/deployment/boxes<blinkin' cursor here>
```

**Comment by TizianoPerrucci** [comment]
@iwein I'm not sure if this is still a pain. Few features have been implemented that can help in those situations.

Since few releases entering playbook path got easier because the full path is not necessary anymore, so you could use a relative path (relative to the directory where you started Prudentia). That means for instance you could first cd into the directory where the playbook is located and then just use the filename when registering the Prudentia box.

Moreover command history across Prudentia session can be leveraged just using arrow up. If you previously entered an incomplete path press arrow up and you can get it back and complete it.

Hope those things alleviate the pain you experienced. I close this issue for now and see if others will come up.

**Comment by iwein** [comment]
It would still be valuable to have this, users can make errors when typing and cancelling the process with an error if they do is harsh. If you catch the error and ask the question again (retry/abort style), then it would be better.

**Comment by TizianoPerrucci** [comment]
Regarding the retrying mechanism I agree, is in the dev pipeline https://trello.com/c/i2u5ZhlC/169-implement-retries-for-all-inputs; but I won't re-enter what the user entered previously.

**Comment by iwein** [comment]
That's fair, I'd just arrow up then :)
