### ISSUE TITLE
Keys should be updatable when phoenixing in `prudentia digital-ocean`

### ISSUE THREAD

**Issue by iwein** [StarterSquad/prudentia#26]
Reproduce: 

- register box in `prudentia digital-ocean`
- phoenix box

expected: there is no way to change the keys that were set during registration

actual: the log outputs that keys are available and selected (which isn't true)

**Comment by TizianoPerrucci** [comment]
Indeed there is no way to change the ssh keys that have been used during droplet creation, but at the same time is not possible to know, trough the Digital Ocean API, which ones were used.

So when registering an existing droplet we are not gonna ask for ssh keys anymore, leaving the keys in the box definition undefined.

This will not create any issue when phoenixing the droplet because Digital Ocean will automatically use the original ones; on the other end creating a droplet (after destroying it) will find the ssh keys not valued and ask to reconfigure the box.
