### ISSUE TITLE
Handle db migrations on update

### ISSUE THREAD

**Issue by dmitryevseev** [StarterSquad/prudentia#9]
In the process of project development I often face the need of updating db structure.
E. g. I need to run:
```
db.groups.update({}, {$rename: {"name": "info"}}, false, true);
```

How do you usually handle it? Does prudentia have something already?

**Comment by TizianoPerrucci** [comment]
Hi @dmitryevseev I've updated the Prudentia examples and as you can see now that the example `app` box (https://github.com/StarterSquad/prudentia/blob/develop/examples/boxes/app.yml) uses a database component.

This component, beside being based on MySQL (does not really matter for the sake of the example), shows you how to manage in a simple way sql increments. When running the db provisioning the sql increments are transferred to the target machine together with the upgrade.sh script that will keep track of the last increment that was run.

I would not use this in production because you could have multiple nodes and would be better to keep the information of which sql increments have been run into a version table in the db. Moreover would be safer to have an upgrade script as well as a downgrade script for rollbacks.

For instance tools like https://sqlalchemy-migrate.readthedocs.org do already this but probably you are not using python/sql alchemy in your settings right now.

I hope I gave you some idea on how to solve your problem.
